{
  "hash": "112bac6baee97850ccd91a64d830befd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Sketch for assignment using exercise 1\"\nauthor:\n  - name: Jørn I. Halvorsen\n    id: JIH\n  - name: Irina Nikolskaja Roddvik\n    id: IR\nbibliography: abc.bib\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"assignmentQandA.R\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n:::\n\n\n\n# Inroduction\n\nWould like to refer to [@wickham2023r] abc\n\nModel 1: One variable and linear\n$$price_i=\\beta_0+\\beta_1 mileage_i + u_i$$\n\nModel 2: Two variables and non-linear\n$$price_i=\\beta_0+\\beta_1 mileage_i+ \\beta_2 mileage_i^2 + u_i$$\n\n# Data \n\n# Results\n\n## Estimations\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidres1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term         estimate std.error statistic  p.value\n  <chr>           <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept) 18226.    1323.         13.8  1.46e-16\n2 mileage        -0.108    0.0419     -2.58 1.38e- 2\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglares1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>   <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.146         0.124 6085.      6.66  0.0138     1  -414.  835.  840.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\n\n## Predictions\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_1 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2         3         4 \n18220.743 16593.372 15849.341  4122.125 \n```\n\n\n:::\n:::\n\n\n\n- The first predicted value equal to 18220.743\n- The second predicted value equal to 16593.372\n- ...\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2         3         4 \n19865.213 16537.906 15205.588  9865.851 \n```\n\n\n:::\n:::\n\n\n\n# Appendix\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(\"images/price_mileage.png\")\n```\n\n::: {.cell-output-display}\n![Model1](images/price_mileage.png){#fig-mod1 width=266}\n:::\n:::\n\n\n\n@fig-mod1 shows GRETL output ...\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# predict()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::knit_exit()\n```\n:::\n",
    "supporting": [
      "assignment_QandA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}